apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  ports:
    - port: 4001
      name: http
  clusterIP: None
  selector:
    app: chat-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chat-service
spec:
  serviceName: "chat-service"
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: chat-service:latest
          ports:
            - containerPort: 4001
              name: http
          env:
            - name: PORT
              value: "4001"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: admin-jwt-secret
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: redis-password
